spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.199.121/setsuna_test_db?useSSL=true
    username: setsuna
    password: Setsuna_Pisces313!
mybatis:
  config-location:
    map-underscore-to-camel-case: true # book_id => bookId,book_name=> bookName
    type-aliases-package: com.example.ssm1.domain #别名
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

